export { InventarioPage } from "./inventory";
export { PedidosPage } from "./order";
export { CajaPage } from "./sale";
export { EntregasPage } from "./dispatch";
export { ProduccionPage } from "./production";
export { OrderProductionPage } from "./production-orders";
export { UserPage } from "./users";
export { DashboardPage } from "./dashboard";
export { ReconocimientosPage } from "./recognitions";